debug secret

diff --git a/.github/workflows/sast-scan.yml b/.github/workflows/sast-scan.yml
--- a/.github/workflows/sast-scan.yml
+++ b/.github/workflows/sast-scan.yml
@@ -24,13 +24,20 @@ jobs:
         run: |
           wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.1/dependency-check-12.1.1-release.zip
           unzip -q dependency-check-12.1.1-release.zip -d $HOME/dependency-check
-
+      - name: Verify Secret
+        run: |
+          if [ -z "${{ secrets.WORKSHOP6_NVD_API_KEY }}" ]; then
+           echo "SECRET_MISSING"
+           exit 1
+          else
+           echo "SECRET_FOUND"
+          fi
       - name: Run OWASP Dependency-Check
         run: |
           chmod +x $HOME/dependency-check/dependency-check/bin/dependency-check.sh
           $HOME/dependency-check/dependency-check/bin/dependency-check.sh \
             --project "bitcoin" \
-            --nvd-api-key ${{ secrets.WORKSHOP6_NVD_API_KEY }} \
+            --nvdApiKey ${{ secrets.WORKSHOP6_NVD_API_KEY }} \
             --out . \
             --scan . \
             --disableOssIndex
